# Generated by Django 3.1.5 on 2021-05-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='insta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.IntegerField()),
                ('followee', models.IntegerField()),
                ('name', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=540, null=True)),
                ('Bio', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=100, null=True)),
                ('contact', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
